### ISSUE TITLE
 ⨯ RollupError: Unexpected character '�'

### ISSUE THREAD

**Issue by samijaber** [huozhi/bunchee#313]
Reproduction steps:

- go to https://github.com/BuilderIO/hydration-overlay/blob/fix/webpack-import/ branch
- `pnpm install`
- `cd packages/lib`
- run `bunchee src/next-plugin.ts`

I get the error:

```
1: ����
       (        ���__TEXT�__text...
   ^
��@����/���3�/���/��+��!��'��U��#���9�A��W��}��S��{�*}��O������J...
3: �R�7����jA��+�)@��;�3�RV�RI�R���7@�����7���N��M��    �!��C���s������-��      D8�s�...
 ⨯ RollupError: Unexpected character '�'
    at error (/Users/samijaber/code/work/react-hydration-overlay/node_modules/.pnpm/rollup@4.8.0/node_modules/rollup/dist/shared/parseAst.js:279:30)
    at nodeConverters (/Users/samijaber/code/work/react-hydration-overlay/node_modules/.pnpm/rollup@4.8.0/node_modules/rollup/dist/shared/parseAst.js:2147:9)
    at convertNode (/Users/samijaber/code/work/react-hydration-overlay/node_modules/.pnpm/rollup@4.8.0/node_modules/rollup/dist/shared/parseAst.js:1032:12)
    at convertProgram (/Users/samijaber/code/work/react-hydration-overlay/node_modules/.pnpm/rollup@4.8.0/node_modules/rollup/dist/shared/parseAst.js:1023:48)
    at Object.parseAstAsync (/Users/samijaber/code/work/react-hydration-overlay/node_modules/.pnpm/rollup@4.8.0/node_modules/rollup/dist/shared/parseAst.js:2213:20)
    at async Module.tryParseAsync (/Users/samijaber/code/work/react-hydration-overlay/node_modules/.pnpm/rollup@4.8.0/node_modules/rollup/dist/shared/rollup.js:14921:21)
    at async Module.setSource (/Users/samijaber/code/work/react-hydration-overlay/node_modules/.pnpm/rollup@4.8.0/node_modules/rollup/dist/shared/rollup.js:14502:35)
    at async ModuleLoader.addModuleSource (/Users/samijaber/code/work/react-hydration-overlay/node_modules/.pnpm/rollup@4.8.0/node_modules/rollup/dist/shared/rollup.js:18811:13)
```

**Comment by huozhi** [comment]
Hi that's because you're bundling `webpack` without externalizing it, I post in https://github.com/huozhi/bunchee/issues/312#issuecomment-1861409565 as well
