### ISSUE TITLE
bunchee --prepare adds invalid Object to `main` and `module`

### ISSUE THREAD

**Issue by samijaber** [huozhi/bunchee#379]
reproduction:
- clone https://github.com/samijaber/nextjs-monorepo/commit/d5867709e83672c6ceb073bff3c6bd118a4dceeb
- try to `pnpm bunchee`
- remove the `main` and `module` from `lib/package.json`
- run `pnpm bunchee --prepare` to see them show up again.

Issue:
running `bunchee --prepare` on a barebones project, I. get:

![CleanShot 2024-01-10 at 15 20 57@2x](https://github.com/huozhi/bunchee/assets/1393142/c202311f-4f08-4cb4-a1d9-5dd7ef080d18)

which is invalid, and causes `bunchee` itself to crash when trying to build subsequently:

```
⨯ TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Object
    at validateString (node:internal/validators:162:11)
    at Object.extname (node:path:1389:5)
    at hasCjsExtension (/Users/samijaber/code/work/bug-repros/nextjs-monorepo/node_modules/.pnpm/bunchee@4.3.2_typescript@5.3.3/node_modules/bunchee/dist/index.js:209:59)
    at getExportPaths (/Users/samijaber/code/work/bug-repros/nextjs-monorepo/node_modules/.pnpm/bunchee@4.3.2_typescript@5.3.3/node_modules/bunchee/dist/index.js:561:37)
    at Object.bundle (/Users/samijaber/code/work/bug-repros/nextjs-monorepo/node_modules/.pnpm/bunchee@4.3.2_typescript@5.3.3/node_modules/bunchee/dist/index.js:1338:25)
    at async run (/Users/samijaber/code/work/bug-repros/nextjs-monorepo/node_modules/.pnpm/bunchee@4.3.2_typescript@5.3.3/node_modules/bunchee/dist/bin/cli.js:464:9)
    at async main (/Users/samijaber/code/work/bug-repros/nextjs-monorepo/node_modules/.pnpm/bunchee@4.3.2_typescript@5.3.3/node_modules/bunchee/dist/bin/cli.js:493:5) {
  code: 'ERR_INVALID_ARG_TYPE'
```

**Comment by huozhi** [comment]
Fixed in 4.3.3
