### ISSUE TITLE
rollup-plugin-dts unable to resolve some types

### ISSUE THREAD

**Issue by juliusmarminge** [huozhi/bunchee#437]
### Reproduce

1. Checkout the following repo and branch: https://github.com/pingdotgg/uploadthing/tree/expoo
2. Install deps: `pnpm install`
4. Run build (main package is enough): `cd packages/uploadthing && pnpm build`
  - build should pass
5. Remove `@ts-ignore` directives in `src/express.ts#46` and `src/express#L98`
6. Build again: `pnpm build`
7. See error:

```sh
pnpm build

> uploadthing@6.3.1 build /Users/julius/dev/uploadthing/packages/uploadthing
> bunchee

src/express.ts(46,27): error TS7006: Parameter 'req' implicitly has an 'any' type.
src/express.ts(46,32): error TS7006: Parameter 'res' implicitly has an 'any' type.
src/express.ts(95,20): error TS7006: Parameter '_req' implicitly has an 'any' type.
src/express.ts(95,26): error TS7006: Parameter 'res' implicitly has an 'any' type.

⨯ RollupError: Failed to compile. Check the logs above.
    at Object.error (/Users/julius/dev/uploadthing/node_modules/.pnpm/rollup@4.9.6/node_modules/rollup/dist/shared/parseAst.js:279:30)
    at Object.error (/Users/julius/dev/uploadthing/node_modules/.pnpm/rollup@4.9.6/node_modules/rollup/dist/shared/rollup.js:820:32)
    at Object.error (/Users/julius/dev/uploadthing/node_modules/.pnpm/rollup@4.9.6/node_modules/rollup/dist/shared/rollup.js:18688:42)
    at generateDtsFromTs (/Users/julius/dev/uploadthing/node_modules/.pnpm/rollup-plugin-dts@6.1.0_rollup@4.9.6_typescript@5.3.3/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.cjs:1857:30)
    at Object.transform (/Users/julius/dev/uploadthing/node_modules/.pnpm/rollup-plugin-dts@6.1.0_rollup@4.9.6_typescript@5.3.3/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.cjs:1866:38)
    at /Users/julius/dev/uploadthing/node_modules/.pnpm/rollup@4.9.6/node_modules/rollup/dist/shared/rollup.js:1005:40
 ELIFECYCLE  Command failed with exit code 1.
```

As can be seen in your editor, types are resolved properly:

![CleanShot 2024-01-28 at 23 45 50](https://github.com/huozhi/bunchee/assets/51714798/d9deda40-02d0-4102-b33c-5800ccd90a2a)

**Comment by huozhi** [comment]
I think I saw this error while testing in another app, it's related to a tsconfig flag `preserveSymlinks`, but I can'f find the extend parent tsconfig on npm. Not sure if that's disabled somewhere?

**Comment by juliusmarminge** [comment]
Its a local package https://github.com/pingdotgg/uploadthing/tree/main/tooling/tsconfig

**Comment by huozhi** [comment]
It built successfully for me locally 🤔

**Comment by juliusmarminge** [comment]
> It built successfully for me locally 🤔 

Even after removing ts-ignore comments?

**Comment by huozhi** [comment]
Oh missed that step.

It seems similar to this issue https://github.com/DefinitelyTyped/DefinitelyTyped/issues/53397 , that the types cannot easily being resolved due to the express types defs.

```ts
/// <reference types="express-serve-static-core" />
/// <reference types="serve-static" />
```

I installed `@types/express-serve-static-core` as dev dep and it works
