### ISSUE TITLE
Unexpected token `implements`

### ISSUE THREAD

**Issue by wendellhu95** [huozhi/bunchee#47]
Trying to build a TypeScript file. `implements` keyword seems not to be supported.

```
yarn run v1.22.10
$ bunchee src/index.ts -m --no-sourcemap
/home/ubuntu/repos/wedi/src/index.ts .ts true
 9: } from './typings';
10: 
11: export class DependencyCollection implements Disposable {
                                      ^
12:     public disposed: boolean = false;
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (/home/ubuntu/repos/wedi/node_modules/rollup/dist/shared/node-entry.js:5400:30)
    at Module.error (/home/ubuntu/repos/wedi/node_modules/rollup/dist/shared/node-entry.js:9820:16)
    at tryParse (/home/ubuntu/repos/wedi/node_modules/rollup/dist/shared/node-entry.js:9713:23)
    at Module.setSource (/home/ubuntu/repos/wedi/node_modules/rollup/dist/shared/node-entry.js:10076:33)
    at /home/ubuntu/repos/wedi/node_modules/rollup/dist/shared/node-entry.js:12362:20
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
```

**Comment by huozhi** [comment]
Can you provide a minial reproduction for this? I tried a simple snippet locally it compiles well with bunchee.

input
```ts
interface D {
 f(): void;
}

export default class A implements D {
 f() { console.log(111) }

}
```

output
```js
var A = /** @class */ (function () {
    function A() {
    }
    A.prototype.f = function () { console.log(111); };
    return A;
}());
```
